# Generated by Django 4.2.5 on 2023-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
